# This workflow will build a MuleSoft project and deploy to CloudHub
name: Setup JDK Maven and Git
description: setting up the required tools

inputs:
  muleMavenEEUser:
    required: true
    type: string
  muleMavenEEPwd:
    required: true
  ghUser:
    required: true
    type: string
  ghPwd:
    required: true
  anypointClientId:
    required: true
  anypointClientSecret:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    # add the required maven-repos and settings
    - name: maven-settings-xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: |
          [
            {
              "id": "MuleRepository", 
              "name": "MuleRepository", 
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/", 
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
              "id": "github", 
              "name": "CKWParentPOM", 
              "url": "https://maven.pkg.github.com/CKWAG/ckw-mule-parent-pom",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }]
        servers: |
          [
            { 
              "id": "MuleRepository", 
              "username": "${{ inputs.muleMavenEEUser }}", 
              "password": "${{ inputs.muleMavenEEPwd }}" 
            },
            { 
              "id": "github", 
              "username": "${{ inputs.ghUser }}", 
              "password": "${{ inputs.ghPwd }}" 
            },
            {
              "id": "anypoint-exchange",
              "username": "~~~Client~~~", 
              "password": "${{ inputs.anypointClientId }}~?~${{ inputs.anypointClientSecret }}" 
            }
          ]
         
    # required since the mvn release:prepare will make some commits with git
    - name: set git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global merge.ff only